const Book = require('./Book.js');
const Ebook = require('./Ebook.js');
const book1 = new Book("Война и мир", "Лев Толстой", 1869);
const book2 = new Book("Преступление и наказание", "Фёдор Достоевский", 1867);
const book3 = new Book("Мастер и Маргарита", "Михаил Булгаков", 1967);
const book4 = new Book("Евгений Онегин", "Александр Пушкин", 1830);
const ebook1 = new Ebook("Муму", "Иван Тургенев", 1854, "PDF");
book1.printInfo();
book2.printInfo();
book3.printInfo();
book4.printInfo();
ebook1.printInfo();
const books = [book1, book2, book3, book4, ebook1];
const oldestBook = Book.getOldestBook(books);
oldestBook.printInfo();
const convertedEbook1 = Ebook.bookConvert(book1, "PDF");
convertedEbook1.printInfo();
const convertedEbook2 = Ebook.bookConvert(book2, "PDF");
convertedEbook2.printInfo();
const convertedEbook3 = Ebook.bookConvert(book3, "PDF");
convertedEbook3.printInfo();
const convertedEbook4 = Ebook.bookConvert(book4, "PDF");
convertedEbook4.printInfo();